create table if not exists public.engineering_requests (
  id uuid primary key default gen_random_uuid(),
  request_number bigint generated by default as identity unique,
  broker_user_id uuid not null references auth.users (id) on delete cascade,
  property_kind text not null check (property_kind in ('Novo', 'Usado', 'Terreno')),
  property_value numeric(14, 2) not null,
  contact_phone text not null,
  accompanying_name text not null,
  status text not null default 'pending'
    check (status in ('pending', 'in_progress', 'completed', 'cancelled')),
  form_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists engineering_requests_broker_user_id_idx
  on public.engineering_requests (broker_user_id);

create index if not exists engineering_requests_created_at_idx
  on public.engineering_requests (created_at desc);

drop trigger if exists set_engineering_requests_updated_at on public.engineering_requests;

create trigger set_engineering_requests_updated_at
before update on public.engineering_requests
for each row
execute function public.set_updated_at();

alter table public.engineering_requests enable row level security;

drop policy if exists "engineering_requests_select_own_or_admin" on public.engineering_requests;
create policy "engineering_requests_select_own_or_admin"
on public.engineering_requests
for select
to authenticated
using (
  broker_user_id = auth.uid()
  or public.is_admin()
);

drop policy if exists "engineering_requests_insert_own_or_admin" on public.engineering_requests;
create policy "engineering_requests_insert_own_or_admin"
on public.engineering_requests
for insert
to authenticated
with check (
  broker_user_id = auth.uid()
  or public.is_admin()
);

drop policy if exists "engineering_requests_update_own_or_admin" on public.engineering_requests;
create policy "engineering_requests_update_own_or_admin"
on public.engineering_requests
for update
to authenticated
using (
  broker_user_id = auth.uid()
  or public.is_admin()
)
with check (
  broker_user_id = auth.uid()
  or public.is_admin()
);

drop policy if exists "engineering_requests_delete_own_or_admin" on public.engineering_requests;
create policy "engineering_requests_delete_own_or_admin"
on public.engineering_requests
for delete
to authenticated
using (
  broker_user_id = auth.uid()
  or public.is_admin()
);

create table if not exists public.engineering_request_documents (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references public.engineering_requests (id) on delete cascade,
  document_key text not null,
  original_filename text not null,
  storage_location text not null,
  content_type text not null,
  size_bytes bigint not null,
  uploaded_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  unique (request_id, document_key)
);

create index if not exists engineering_request_documents_request_id_idx
  on public.engineering_request_documents (request_id);

alter table public.engineering_request_documents enable row level security;

drop policy if exists "engineering_request_documents_select_own_or_admin" on public.engineering_request_documents;
create policy "engineering_request_documents_select_own_or_admin"
on public.engineering_request_documents
for select
to authenticated
using (
  exists (
    select 1
    from public.engineering_requests
    where engineering_requests.id = engineering_request_documents.request_id
      and (
        engineering_requests.broker_user_id = auth.uid()
        or public.is_admin()
      )
  )
);

drop policy if exists "engineering_request_documents_insert_own_or_admin" on public.engineering_request_documents;
create policy "engineering_request_documents_insert_own_or_admin"
on public.engineering_request_documents
for insert
to authenticated
with check (
  exists (
    select 1
    from public.engineering_requests
    where engineering_requests.id = engineering_request_documents.request_id
      and (
        engineering_requests.broker_user_id = auth.uid()
        or public.is_admin()
      )
  )
);

drop policy if exists "engineering_request_documents_update_own_or_admin" on public.engineering_request_documents;
create policy "engineering_request_documents_update_own_or_admin"
on public.engineering_request_documents
for update
to authenticated
using (
  exists (
    select 1
    from public.engineering_requests
    where engineering_requests.id = engineering_request_documents.request_id
      and (
        engineering_requests.broker_user_id = auth.uid()
        or public.is_admin()
      )
  )
)
with check (
  exists (
    select 1
    from public.engineering_requests
    where engineering_requests.id = engineering_request_documents.request_id
      and (
        engineering_requests.broker_user_id = auth.uid()
        or public.is_admin()
      )
  )
);

drop policy if exists "engineering_request_documents_delete_own_or_admin" on public.engineering_request_documents;
create policy "engineering_request_documents_delete_own_or_admin"
on public.engineering_request_documents
for delete
to authenticated
using (
  exists (
    select 1
    from public.engineering_requests
    where engineering_requests.id = engineering_request_documents.request_id
      and (
        engineering_requests.broker_user_id = auth.uid()
        or public.is_admin()
      )
  )
);
