create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.proposals (
  id uuid primary key default gen_random_uuid(),
  proposal_number bigint generated by default as identity unique,
  broker_user_id uuid not null references auth.users (id) on delete cascade,
  broker_name text not null,
  client_name text not null,
  client_cpf text,
  client_email text,
  client_phone text,
  property_type text,
  property_city text,
  property_state text,
  additional_info text,
  form_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists proposals_broker_user_id_idx
  on public.proposals (broker_user_id);

create index if not exists proposals_created_at_idx
  on public.proposals (created_at desc);

drop trigger if exists set_proposals_updated_at on public.proposals;

create trigger set_proposals_updated_at
before update on public.proposals
for each row
execute function public.set_updated_at();

alter table public.proposals enable row level security;

drop policy if exists "proposals_select_own" on public.proposals;
create policy "proposals_select_own"
on public.proposals
for select
to authenticated
using (broker_user_id = auth.uid());

drop policy if exists "proposals_insert_own" on public.proposals;
create policy "proposals_insert_own"
on public.proposals
for insert
to authenticated
with check (broker_user_id = auth.uid());

drop policy if exists "proposals_update_own" on public.proposals;
create policy "proposals_update_own"
on public.proposals
for update
to authenticated
using (broker_user_id = auth.uid())
with check (broker_user_id = auth.uid());

drop policy if exists "proposals_delete_own" on public.proposals;
create policy "proposals_delete_own"
on public.proposals
for delete
to authenticated
using (broker_user_id = auth.uid());

create table if not exists public.proposal_documents (
  id uuid primary key default gen_random_uuid(),
  proposal_id uuid not null references public.proposals (id) on delete cascade,
  filename text not null,
  original_filename text not null,
  storage_location text not null,
  content_type text not null,
  size_bytes bigint not null,
  uploaded_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists proposal_documents_proposal_id_idx
  on public.proposal_documents (proposal_id);

alter table public.proposal_documents enable row level security;

drop policy if exists "proposal_documents_select_own" on public.proposal_documents;
create policy "proposal_documents_select_own"
on public.proposal_documents
for select
to authenticated
using (
  exists (
    select 1
    from public.proposals
    where proposals.id = proposal_documents.proposal_id
      and proposals.broker_user_id = auth.uid()
  )
);

drop policy if exists "proposal_documents_insert_own" on public.proposal_documents;
create policy "proposal_documents_insert_own"
on public.proposal_documents
for insert
to authenticated
with check (
  exists (
    select 1
    from public.proposals
    where proposals.id = proposal_documents.proposal_id
      and proposals.broker_user_id = auth.uid()
  )
);

drop policy if exists "proposal_documents_delete_own" on public.proposal_documents;
create policy "proposal_documents_delete_own"
on public.proposal_documents
for delete
to authenticated
using (
  exists (
    select 1
    from public.proposals
    where proposals.id = proposal_documents.proposal_id
      and proposals.broker_user_id = auth.uid()
  )
);

drop policy if exists "proposal_documents_update_own" on public.proposal_documents;
create policy "proposal_documents_update_own"
on public.proposal_documents
for update
to authenticated
using (
  exists (
    select 1
    from public.proposals
    where proposals.id = proposal_documents.proposal_id
      and proposals.broker_user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.proposals
    where proposals.id = proposal_documents.proposal_id
      and proposals.broker_user_id = auth.uid()
  )
);
